#!/bin/bash

echo -e "\033[33mcleaning up gitfluss builds...\033[0m"

if [[ -d ./build/ ]]
then
    rm ./build/ -rf
fi

if [[ -d ./bin/ ]]
then
    rm ./bin/ -rf
fi

if [[ -d ./build/ ]]
then
    rm ./build/ -rf
fi

for out in callgrind.*
do
    if [[ ! -f $out ]]
    then
        continue;
    fi

    rm $out
done

echo -e "\033[32mcleaned gitfluss!\n\033[0m"
