#!/bin/bash

if [[ ! -d "./obj/" ]]
then
    mkdir ./obj/
fi

if [[ ! -d "./build/" ]]
then
    mkdir ./build/
fi

if [[ ! -d "./bin/" ]]
then
    mkdir ./bin/
fi

if [[ $1 = "" ]]
then
    build="release"
else
    build=$1
fi

args="-DBUILD_LINUX
vendor/puddle/src/string_view.c \
vendor/puddle/src/linux_pd_path.c \
src/gitfluss_main.c \
src/gitfluss_parsing.c \
src/linux_gitfluss_platform.c \
-Iinclude/ \
-Ivendor/puddle/include/ \
-Ivendor/libgit2/include/ \
-lgit2 \
-O2"

function compile()
{
    echo ""
    echo -e "\033[36mcompiling gitfluss...\033[0m"
    echo ""

    premake5 --version > /dev/null
    if [[ $? != 0 ]]
    then
        echo "premake5 binary not found."
        echo "trying to identify a compiler..."

        clang --version > /dev/null
        if [[ $? = 0 ]]
        then
            echo "found clang."
            echo "building release build with default flags:"
            echo "clang $args"
            clang $args

            if [[ ! -d ./bin/release ]]
            then
                mkdir ./bin/release
            fi

            mv ./a.out ./bin/release/gitfluss
        fi

        gcc --version > /dev/null
        if [[ $? = 0 ]]
        then
            echo "found gcc."
            echo "building release build with default flags:"
            echo "gcc $args"
            gcc $args

            if [[ ! -d ./bin/release ]]
            then
                mkdir ./bin/release
            fi

            mv ./a.out ./bin/release/gitfluss
        fi

        return;
    fi

    premake5 gmake

    pushd ./build/ > /dev/null
    make config=$build\_linux
}

if [[ $build = "asan" ]] || [[ $build = "debug" ]] || [[ $build = "release" ]]
then

    ldconfig -p | grep "libgit2.so" > /dev/null
    if [[ $? != 0 ]]
    then
        echo -e "\033[33m\nWARNING: libgit2.so could not be located on the system."
        echo -e "Compiling from source...\n\033[0m"

        if [[ ! -d "./vendor/libgit2/src/" ]]
        then
            echo -ne "\033[31m\nERROR: git2 submodule cannot be found. Repository was "
            echo -e "cloned incorrectly, please use '--recurse' when cloning.\033[0m"
            exit -6;
        fi

        cmake --version > /dev/null
        if [[ $? != 0 ]]
        then
            echo -ne "\033[31m\nERROR: CMake not found. Please provide a cmake binary "
            echo -e "in your path in order to build libgit2 from source.\033[0m"
        fi

        pushd ./vendor/libgit2/ > /dev/null
        if [[ ! -d "./build/" ]]
        then
            mkdir ./build/
        fi
        cd build

        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF
        cmake --build .

        if [[ $? != 0 ]]
        then
            echo -e "\033[31m\nERROR: failed to compile libgit2 from source.\n\033[0m"
            popd > /dev/null
            exit -7;
        fi

        popd > /dev/null
    fi

    compile
else
    echo -e "\033[31m\nERROR: invalid make config: '$build'.\033[0m"
    popd > /dev/null
    exit -2;
fi

if [[ $? != 0 ]]
then
    echo -e "\033[31m\nERROR: failed to compile gitfluss.\n\033[0m"
    popd > /dev/null
    exit -1;
fi

echo -e "\n"

if [[ $2 = "--compile-only" ]]
then
    exit 0;
fi

popd > /dev/null

chmod +x ./bin/$build/gitfluss
./bin/$build/gitfluss
